{% set name = "SSp_Detector" %}
{% set version = "2024.12.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SSp_Detector-{{ version }}.tar.gz
  sha256: 6db5313c43363d2e1a44a42219913c4f0890e30ccadbe0295005da86d1636244

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.9.0
  run:
    - python >=3.9.0
    - mne >=1.2.0
    - numpy >=1.24.3
    - outdated
    - pandas >=2.0.0
    - scipy >=1.11

test:
  imports:
    - SSp_Detector

about:
  home: https://github.com/sjg2203/SSp_Detector
  summary: Sleep spindles detector
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/sjg2203/SSp_Detector/blob/main/README.md
  dev_url: https://github.com/sjg2203/SSp_Detector

extra:
  recipe-maintainers:
    - sjg2203
