{% set name = "ssp_detector" %}
{% set version = "2024.12.13" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d69f82a5c32711b1d2d46c875b64b287e982a242a5aa55ddb8bd3d73c496bb0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - mne >=1.6.0
    - numpy >=1.25.0
    - outdated
    - pandas >=2.2.0
    - scipy >=1.12.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - SSp_Detector

about:
  home: https://github.com/sjg2203/SSp_Detector
  summary: Sleep spindles detector
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/sjg2203/SSp_Detector/blob/main/README.md
  dev_url: https://github.com/sjg2203/SSp_Detector

extra:
  recipe-maintainers:
    - sjg2203
